documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

enhancement:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*"
          - "features/**/*"
  - head-branch:
      - "^feature"

bug:
  - changed-files:
      - any-glob-to-any-file:
          - "fixes/**/*"

question:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/questions/**/*"

invalid:
  - changed-files:
      - any-glob-to-any-file:
          - "*.tmp"

help wanted:
  - changed-files:
      - any-glob-to-any-file:
          - "help/**/*"

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          
javascript:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "**/*.js"
          - "**/*.mjs"
          - "**/*.cjs"
